### ISSUE TITLE
ActiveSupport dependency

### ISSUE THREAD

**Issue by gogainda** [oddlyfunctional/know_it_all#3]
Are considering to remove ActiveSupport dependency in favor Hanami::Utils?
[Why? ](https://github.com/thoughtbot/factory_girl/issues/903)

**Comment by oddlyfunctional** [comment]
I'd be glad to change to a smaller dependency, I just used what I already knew to release sooner. :)
I'll probably just extract the `camelize` logic directly, though, since it's the only feature I'm using (for now).
